services:
  db:
    image: postgres:16-alpine
    container_name: lead2buy-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lead2buy-network

  lead2buy-api:
    build:
      # --- ALTERAÇÃO PRINCIPAL AQUI ---
      # Aponta o contexto de build para a pasta da API, resolvendo o erro.
      context: ./Lead2Buy.API
      dockerfile: Dockerfile
      # --- FIM DA ALTERAÇÃO ---
    container_name: lead2buy-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
    depends_on:
      - db
    networks:
      - lead2buy-network

  lead2buy-frontend:
    build:
      context: ./lead2buy-frontend
      dockerfile: Dockerfile
    container_name: lead2buy-frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - lead2buy-network

  nginx:
    image: nginx:latest
    container_name: lead2buy-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx/lead2buy-api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lead2buy-api
      - lead2buy-frontend
    networks:
      - lead2buy-network

networks:
  lead2buy-network:
    driver: bridge

volumes:
  postgres_data: