services:
  # Serviço da API .NET
  api:
    build:
      context: ./Lead2Buy.API
      dockerfile: Dockerfile
    container_name: lead2buy_api
    ports:
      - "5000:8080"
    env_file:
      - .env
    depends_on:
      - db
      - ollama
      - redis
    restart: unless-stopped
    networks:
      - lead2buy-net

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:latest
    container_name: lead2buy_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - lead2buy-net

  # Serviço do Ollama com o modelo (Simplificado)
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: lead2buy_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - lead2buy-net
  
  # Serviço do Redis
  redis:
    image: "redis:alpine"
    container_name: lead2buy_redis
    restart: unless-stopped
    networks:
      - lead2buy-net

volumes:
  postgres_data:
  ollama_data:

networks:
  lead2buy-net:
    driver: bridge