services:
  api:
    build:
      context: ./Lead2Buy.API
      dockerfile: Dockerfile
    container_name: lead2buy_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - CORS_ORIGIN=https://www.rvwtech.com.br
      - OcrApiKey=K87679144388957
      - MailjetApiKey=49fc3e132d31ec61110c79651eb9a22b
      - MailjetApiSecret=541c19897679fd21aef0ae3ae9625e03
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=lead2buy_db;Username=postgres;Password='@RVWSecretLeadsData'
      - RedisConnectionString=redis:6379
      # --- AQUI ESTÁ A CORREÇÃO FINAL PARA O CRASH ---
      - Jwt__Issuer=Lead2BuyAPI
      - Jwt__Audience=Lead2BuyUsers
      - Jwt__Key=UMA_CHAVE_SECRETA_SUPER_LONGA_E_DIFICIL_DE_ADIVINHAR_PARA_PRODUCAO_123!@#
    depends_on:
      - db
      - ollama
      - redis
    restart: unless-stopped
    networks:
      - lead2buy-net

  db:
    image: postgres:latest
    container_name: lead2buy_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - lead2buy-net

  ollama:
    image: ollama/ollama
    container_name: lead2buy_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - lead2buy-net
  
  redis:
    image: "redis:alpine"
    container_name: lead2buy_redis
    restart: unless-stopped
    networks:
      - lead2buy-net

volumes:
  postgres_data:
  ollama_data:

networks:
  lead2buy-net:
    driver: bridge