# Sem 'version' e usando postgres:16-alpine, como discutimos
services:
  db:
    image: postgres:16-alpine
    container_name: lead2buy-db
    restart: always
    # Esta seção garante que as variáveis do seu .env sejam usadas para criar o banco
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lead2buy-network

  lead2buy-api:
    build:
      context: .
      dockerfile: Lead2Buy.API/Dockerfile
    container_name: lead2buy-api
    restart: always
    ports:
      - "8080:8080"
    # Esta seção garante que a API se conecte ao banco usando as credenciais do .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DB_HOST=db
      - DB_PORT=5432
      # --- CREDENCIAIS CORRIGIDAS ---
      # A API usa essas variáveis para montar a string de conexão.
      # Elas são lidas diretamente do seu arquivo .env
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      # --- FIM DA CORREÇÃO ---
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
    depends_on:
      - db
    networks:
      - lead2buy-network

  lead2buy-frontend:
    build:
      context: ./lead2buy-frontend
      dockerfile: Dockerfile
    container_name: lead2buy-frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - lead2buy-network

  nginx:
    image: nginx:latest
    container_name: lead2buy-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx/lead2buy-api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lead2buy-api
      - lead2buy-frontend
    networks:
      - lead2buy-network

networks:
  lead2buy-network:
    driver: bridge

volumes:
  postgres_data: