services:
  api:
    build:
      context: ./Lead2Buy.API
      dockerfile: Dockerfile
    container_name: lead2buy_api
    ports:
      - "5000:8080"
    environment:
      # Corrigido: A senha agora está entre aspas para lidar com o caractere '@'
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=lead2buy_db;Username=postgres;Password='@RVWSecretLeadsData'
    env_file:
      - .env
    depends_on:
      - db
      - ollama
      - redis
    restart: unless-stopped
    networks:
      - lead2buy-net

  db:
    image: postgres:latest
    container_name: lead2buy_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - lead2buy-net

  # Simplificado para usar a imagem oficial e garantir estabilidade
  ollama:
    image: ollama/ollama
    container_name: lead2buy_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - lead2buy-net
  
  redis:
    image: "redis:alpine"
    container_name: lead2buy_redis
    restart: unless-stopped
    networks:
      - lead2buy-net

volumes:
  postgres_data:
  ollama_data:

networks:
  lead2buy-net:
    driver: bridge