# Versão final com conexão manual ao banco de dados
services:
  # 1. Nosso serviço "combo" que roda a API e o Ollama juntos
  - type: web
    name: lead2buy-combo
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile.render # Apontando para o Dockerfile na raiz
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      
      # --- CONEXÃO MANUAL DO BANCO DE DADOS ---
      # Substitua os valores abaixo pelos dados do seu Postgres no Render
      - key: DB_HOST
        value: "dpg-d2rgcep5pdvs7399vptg-a" # Ex: dpg-....-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5433" 
      - key: DB_USERNAME
        value: "postgres" # Ex: lead2buy_postgres_user
      - key: DB_PASSWORD
        value: "@RVWSecretLeadsData" # Pegue a senha no dashboard
      - key: DB_NAME
        value: "lead2buy_db" # Ex: lead2buy_db

      - key: RedisConnectionString
        fromService:
          type: redis
          name: lead2buy-redis
          property: connectionString
      - key: CORS_ORIGIN
        value: https://rvwierzba.github.io
      - key: OcrApiKey
        sync: false
      - key: MailjetApiKey
        sync: false
      - key: MailjetApiSecret
        sync: false

  # 2. Serviço de Redis
  - type: redis
    name: lead2buy-redis
    plan: free
    ipAllowList: []

databases:
  # 3. Banco de Dados PostgreSQL
  - name: lead2buy-postgres
    plan: free