services:
  # 1. Serviço da API .NET (Nosso Back-end)
  - type: web
    name: lead2buy-api
    plan: free
    env: docker
    dockerfilePath: ./Lead2Buy.API/Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: lead2buy-postgres
          property: connectionString
      - key: OcrApiKey
        sync: false # Inserir manualmente no painel da Render
      - key: MailjetApiKey
        sync: false # Inserir manualmente no painel da Render
      - key: MailjetApiSecret
        sync: false # Inserir manualmente no painel da Render
      - key: CORS_ORIGIN
        fromService:
          type: web # O tipo do frontend agora é 'web'
          name: lead2buy-frontend
          property: url

  # 2. Serviço do Ollama com IA
  - type: worker
    name: lead2buy-ollama
    plan: free
    env: docker
    dockerfilePath: ./ollama/Dockerfile

  # 3. Serviço do Frontend Vue.js (COM A SINTAXE CORRETA)
  - type: web # <-- A CORREÇÃO ESTÁ AQUI
    name: lead2buy-frontend
    plan: free
    runtime: static # <-- E AQUI
    buildCommand: npm --prefix ./lead2buy-frontend install && npm --prefix ./lead2buy-frontend run build
    staticPublishPath: ./lead2buy-frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: lead2buy-api
          property: url

# --- SEÇÃO CORRETA PARA BANCOS DE DADOS ---
databases:
  # 4. Serviço do Banco de Dados PostgreSQL
  - name: lead2buy-postgres
    plan: free
    databaseName: lead2buy_db
    user: lead2buy_user