# Arquivo de configuração que VAI FUNCIONAR no plano gratuito.
services:
  # 1. API .NET (Ocupando o único espaço de serviço web gratuito)
  - type: web
    name: lead2buy-api
    plan: free
    env: docker
    dockerfilePath: ./Lead2Buy.API/Dockerfile # Caminho correto
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: lead2buy-postgres
          property: connectionString
      - key: RedisConnectionString
        fromService:
          type: redis
          name: lead2buy-redis
          property: connectionString
      - key: CORS_ORIGIN
        value: https://www.rvwtech.com.br
      - key: OcrApiKey
        sync: false
      - key: MailjetApiKey
        sync: false
      - key: MailjetApiSecret
        sync: false

  # 2. Redis
  - type: redis
    name: lead2buy-redis
    plan: free
    ipAllowList: []

databases:
  # 3. PostgreSQL
  - name: lead2buy-postgres
    plan: free