services:
  # 1. Serviço da API .NET
  # Usa o entrypoint.sh dentro do Dockerfile para rodar as migrações
  - type: web
    name: lead2buy-api
    plan: free
    env: docker
    dockerfilePath: ./Lead2Buy.API/Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: lead2buy-postgres
          property: connectionString
      - key: RedisConnectionString
        fromService:
          type: redis
          name: lead2buy-redis
          property: connectionString
      - key: OcrApiKey
        sync: false
      - key: MailjetApiKey
        sync: false
      - key: MailjetApiSecret
        sync: false
      - key: CORS_ORIGIN
        value: https://${lead2buy-frontend.host}

  # 2. Serviço do Ollama com IA
  # Usa o Dockerfile autossuficiente que não depende de scripts externos
  - type: web
    name: lead2buy-ollama
    plan: free
    env: docker
    dockerfilePath: ./ollama/Dockerfile

  # 3. Serviço do Frontend Vue.js
  - type: web
    name: lead2buy-frontend
    runtime: static
    buildCommand: npm --prefix ./lead2buy-frontend install && npm --prefix ./lead2buy-frontend run build
    staticPublishPath: ./lead2buy-frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://${lead2buy-api.host}

  # 4. Serviço de Redis
  - type: redis
    name: lead2buy-redis
    plan: free
    ipAllowList: [] # Permite acesso interno dos seus outros serviços

databases:
  # 5. Serviço do Banco de Dados PostgreSQL
  - name: lead2buy-postgres
    plan: free