# Arquivo final com o super-serviço (API + Ollama) usando o Dockerfile da raiz
services:
  # 1. Nosso serviço "combo" que roda a API e o Ollama juntos
  - type: web
    name: lead2buy-combo
    plan: free
    env: docker
    # Aponta para o novo Dockerfile na raiz do projeto
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: lead2buy-postgres
          property: connectionString
      - key: RedisConnectionString
        fromService:
          type: redis
          name: lead2buy-redis
          property: connectionString
      - key: CORS_ORIGIN
        value: https://rvwierzba.github.io
      - key: OcrApiKey
        sync: false
      - key: MailjetApiKey
        sync: false
      - key: MailjetApiSecret
        sync: false

  # 2. Serviço de Redis
  - type: redis
    name: lead2buy-redis
    plan: free
    ipAllowList: []

databases:
  # 3. Banco de Dados PostgreSQL
  - name: lead2buy-postgres
    plan: free