services:
  - type: web
    name: lead2buy-combo
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: RedisConnectionString
        fromService:
          type: redis
          name: lead2buy-redis
          property: connectionString
      - key: ConnectionStrings__DefaultConnection
        value: "Host=${POSTGRES_HOST};Database=${POSTGRES_DATABASE};Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD};SSL Mode=Require;Trust Server Certificate=true"
      - key: CORS_ORIGIN
        value: https://www.rvwtech.com.br
      - key: OcrApiKey
        sync: false
      - key: MailjetApiKey
        sync: false
      - key: MailjetApiSecret
        sync: false
      - key: Jwt__Key
        value: "cd388ceee7836f3498e43fbbce45d42351dbbfb324e16ed8805c04bd8ce30f85"
      - key: Jwt__Issuer
        value: "https://lead2buy-combo.onrender.com"
      - key: Jwt__Audience
        value: "https://lead2buy-combo.onrender.com"

  - type: redis
    name: lead2buy-redis
    plan: free
    ipAllowList: []

databases:
  - name: lead2buy-postgres
    plan: free
    databaseName: lead2buy
    user: lead2buy_user