# render.yaml corrigido
services:
  - type: web
    name: lead2buy-combo
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: RedisConnectionString
        fromService:
          type: redis
          name: lead2buy-redis
          property: connectionString
      - key: ConnectionStrings__DefaultConnection
        fromService:
          type: postgres
          name: lead2buy-postgres
          property: connectionString
      - key: CORS_ORIGIN
        value: https://www.rvwtech.com.br
      - key: OcrApiKey
        sync: false
      - key: MailjetApiKey
        sync: false
      - key: MailjetApiSecret
        sync: false

  - type: redis
    name: lead2buy-redis
    plan: free
    ipAllowList: []

databases:
  - name: lead2buy-postgres
    plan: free
    databaseName: lead2buy
    user: lead2buy_user