name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        # Garante que o npm install rode dentro da pasta do frontend
        run: npm --prefix lead2buy-frontend install

      - name: Build project
        # Garante que o npm build rode dentro da pasta do frontend
        run: npm --prefix lead2buy-frontend run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Aponta para a pasta 'dist' correta dentro do subdiretório do frontend
          publish_dir: ./lead2buy-frontend/dist